# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_DATABASE=nestEcommerce
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1